# Generated by Django 6.0.6 on 2026-06-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='property_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_flatno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_owner_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_roomno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='allotted_sectionno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HAC.owners'),
        ),
        migrations.AddField(
            model_name='payment',
            name='property_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('allotted', 'Allotted'), ('pending_confirmation', 'Pending Tenant Confirmation'), ('joined', 'Joined / Active')], default='pending', max_length=25),
        ),
    ]
