# Generated by Django 6.0.6 on 2026-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_issue_property_id_issue_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
