# Generated by Django 6.0.6 on 2026-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0004_adminpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('property_type', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20)),
                ('building_layout', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
